#!/bin/zsh

export VBCC=/opt/vbcc
export PATH=$VBCC/bin:$PATH
export DEVA2560=~/dev/bbedit-workspace-a2560

cd $DEVA2560/frOS

# copy latest version of headers to VBCC
cp lib_sys.h $VBCC/targets/a2560-micah/include/mb/
cp a2560_platform.h $VBCC/targets/a2560-micah/include/mb/
cp memory_manager.h $VBCC/targets/a2560-micah/include/mb/
cp theme.h $VBCC/targets/a2560-micah/include/mb/
cp control.h $VBCC/targets/a2560-micah/include/mb/
cp control_template.h $VBCC/targets/a2560-micah/include/mb/
cp font.h $VBCC/targets/a2560-micah/include/mb/
cp window.h $VBCC/targets/a2560-micah/include/mb/
cp general.h $VBCC/targets/a2560-micah/include/mb/
cp text.h $VBCC/targets/a2560-micah/include/mb/
cp bitmap.h $VBCC/targets/a2560-micah/include/mb/

# copy headers to easy-to-share for-vbcc folder
cp lib_sys.h for_vbcc/include/mb/
cp a2560_platform.h for_vbcc/include/mb/
cp memory_manager.h for_vbcc/include/mb/
cp theme.h for_vbcc/include/mb/
cp control.h for_vbcc/include/mb/
cp control_template.h for_vbcc/include/mb/
cp font.h for_vbcc/include/mb/
cp window.h for_vbcc/include/mb/
cp general.h for_vbcc/include/mb/
cp text.h for_vbcc/include/mb/
cp bitmap.h for_vbcc/include/mb/

# make SYS as static lib
vc +/opt/vbcc/config/a2560-4lib-micah -o a2560_sys.lib lib_sys.c memory_manager.c theme.c control_template.c font.c window.c control.c general.c bitmap.c text.c -lm
cp a2560_sys.lib for_vbcc/lib/
mv a2560_sys.lib $VBCC/targets/a2560-micah/lib/


# *************
# Build executables that can be loaded into f68 emulator
# s28 generated by vbcc is almost good enough, but the last line tells loader to run from 0x00000, instead of 0x020000. 
# perl is used to adjust the built .s28 file

# build demo code - SYS
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/sys_demo.s28 lib_sys_demo.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/sys_demo.s28"

# build test code - SYS
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/sys_test.s28 lib_sys_test.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/sys_test.s28"

# build demo code -- FONT
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/font_demo.s28 font_demo.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/font_demo.s28"

# build test code -- FONT
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/font_test.s28 font_test.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/font_test.s28"

# build test code - GENERAL
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/general_test.s28 general_test.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/general_test.s28"

# build demo code - BITMAP
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/bitmap_demo.s28 bitmap_demo.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/bitmap_demo.s28"

# build test code - BITMAP
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/bitmap_test.s28 bitmap_test.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/bitmap_test.s28"

# build demo code - TEXT
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/text_demo.s28 text_demo.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/text_demo.s28"

# build test code - TEXT
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/text_test.s28 text_test.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/text_test.s28"

# build demo code -- WINDOW
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/window_demo.s28 window_demo.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/window_demo.s28"

# build test code -- WINDOW
vc +/opt/vbcc/config/a2560-s28-micahwlib -o build_vbcc/window_test.s28 window_test.c -lm
perl -i -0777 -pe 's/S804000000FB/S804020000FB/' "$DEVA2560/frOS/build_vbcc/window_test.s28"



# renew doxygen docs
#doxygen




echo "\n**************************\nVBCC build script complete\n**************************\n"
