(define memories
  '((memory flash (address (#x20000 . #x4ffff))
            (section (nearcode (#x20000 . #x2a000))
                     code inear ifar cfar switch data_init_table))
    (memory NearRAM (address (#x50000 . #x5ffff))
            (section znear near))
    (memory RAM (address (#x60000 . #x37ffff))
            (section sstack stack zfar far heap))
    (memory Vector (address (#x0000 . #x03ff))
            (section (reset #x0000)))
    (block stack (size #x1000))
    (block sstack (size #x200))
    (block heap (size #x301000))
    (base-address _NearBaseAddress NearRAM #x8000)
    ))